version: '3.3'
services:
  solr1:
    container_name: solr1
    image: solr
    ports:
     - "8981:8983"
    volumes:
      - ./solrconfigsets:/opt/solr/server/solr/configsets
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - solr
  solr2:
    image: solr
    container_name: solr2
    ports:
     - "8982:8983"
    volumes:
      - ./solrconfigsets:/opt/solr/server/solr/configsets
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - solr
  solr3:
    image: solr
    container_name: solr3
    ports:
     - "8983:8983"
    volumes:
      - ./solrconfigsets:/opt/solr/server/solr/configsets
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    ports:
      - 8983:8983
    networks:
      - solr
  zoo1:
    image: zookeeper
    container_name: zoo1
    restart: always
    hostname: zoo1
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr
  zoo2:
    image: zookeeper
    container_name: zoo2
    restart: always
    hostname: zoo2
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr
  zoo3:
    image: zookeeper
    container_name: zoo3
    restart: always
    hostname: zoo3
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr
      
  case-api:
      image: call.center/case_api:latest
      ports:
        - "9000:9001"
      environment:
        - APPLICATION_SECRET=kGb;WxcjXWvzokicH;Qn_9h54q:5v]>38Wg:Q:dwn0<dPWfDKarEi4btAwxtj>wq
        - MONGO_URI=mongodb://mongo.local:27017/dbname?authMode=scram-sha1
        - MONGO_USERNAME=mongo
        - MONGO_PASSWORD=dbpass
        - KAFKA_BROKERS=kafka.local:9092
      links:
        - kafka:kafka.local
        - mongo:mongo.local
  mongo:
    image: mongo
    volumes:
      - /data/db
    ports:

      - "27017:27017"
    environment:
      - MONGODB_USER=mongo
      - MONGODB_DATABASE=dbname
      - MONGODB_PASS=dbpass
  zookeeper:
    image: wurstmeister/zookeeper:3.4.6
  kafka:
    image: johnnypark/kafka-zookeeper
    links:
      - zookeeper
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafkacat:
    image: ryane/kafkacat
    entrypoint:
      - kafkacat
      - -b kafka.local
    links:
      - kafka:kafka.local

networks:
  solr:
